# Generated by Django 5.0.7 on 2024-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcc_num', models.CharField(max_length=5, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('pesnum', models.IntegerField(blank=True, null=True, verbose_name='PESEL')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Męska'), ('K', 'Żeńska')], max_length=10)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('leczenie', models.TextField(blank=True, max_length=300, null=True)),
                ('grkrwi', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcc_num', models.CharField(max_length=5, null=True)),
                ('ecog', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('height', models.CharField(blank=True, max_length=5, null=True)),
                ('weight', models.CharField(blank=True, max_length=3, null=True)),
                ('tumor_num', models.IntegerField(blank=True, default=0, null=True)),
                ('tumor_place', models.TextField(blank=True, default=0, max_length=30, null=True)),
                ('top_diameter', models.IntegerField(blank=True, default=0, null=True)),
                ('li_rads_hcc', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('2', '3'), ('2', '4'), ('2', '5')], max_length=10)),
                ('lab_date', models.CharField(blank=True, max_length=20, null=True)),
                ('albuminy', models.IntegerField(blank=True, null=True)),
                ('inr', models.IntegerField(blank=True, null=True)),
                ('kreatynina', models.IntegerField(blank=True, null=True)),
                ('sod_surowica', models.IntegerField(blank=True, null=True)),
                ('bilirubina_cal', models.IntegerField(blank=True, null=True)),
                ('afp', models.IntegerField(blank=True, null=True)),
                ('plt', models.IntegerField(blank=True, null=True)),
                ('cea', models.IntegerField(blank=True, null=True)),
                ('ca19_9', models.IntegerField(blank=True, null=True)),
                ('cukrzyca', models.CharField(blank=True, choices=[('Y', 'tak'), ('N', 'nie')], max_length=20, null=True)),
                ('nash', models.CharField(blank=True, choices=[('Y', 'tak'), ('N', 'nie')], max_length=20, null=True)),
                ('marskosc', models.CharField(blank=True, choices=[('Y', 'tak'), ('N', 'nie')], max_length=20, null=True)),
                ('wodobrzusze', models.CharField(blank=True, choices=[('1/2', '1/2 stopień'), ('3/4', '3/4 stopień')], max_length=20, null=True)),
                ('encefalopatia', models.CharField(blank=True, choices=[('1/2', '1/2 stopień'), ('3/4', '3/4 stopień')], max_length=20, null=True)),
                ('hbv', models.CharField(blank=True, choices=[('UJ', 'ujemne'), ('DOD', 'dodatnie')], max_length=20, null=True)),
                ('hcv', models.CharField(blank=True, choices=[('UJ', 'ujemne'), ('WYL', 'wyleczone'), ('DOD', 'dodatnie')], max_length=20, null=True)),
            ],
        ),
    ]
