# Generated by Django 5.0.7 on 2024-07-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='hcc_num',
        ),
    ]
