# Generated by Django 5.0.7 on 2024-07-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientprofile_hcc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbase',
            name='kons_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
