# Generated by Django 5.0.7 on 2024-08-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(blank=True, max_length=20, null=True)),
                ('name_1', models.EmailField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
