# Generated by Django 5.0.7 on 2024-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchamodel',
            name='captcha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='captchamodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='captchamodel',
            name='name_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
