# Generated by Django 5.0.7 on 2024-08-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_captchamodel_captcha_alter_captchamodel_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaModel',
        ),
    ]
